// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
// To parse this JSON data, do
//
//     final kjv = kjvFromJson(jsonString);

import 'dart:convert';
import 'package:objectbox/objectbox.dart';

Versions versionsFromJson(String str) {
  final jsonData = json.decode(str);
  return Versions.fromJson(jsonData);
}

// String versionsToJson(Versions data) {
//   final dyn = data.toJson();
//   return json.encode(dyn);
// }

@Entity()
class Versions {
  @Unique(onConflict: ConflictStrategy.replace)
  int id;
  @Id()
  int? uid;
  String versionName;
  final books = ToMany<Book>();

  Versions({
    this.id = 0,
    required this.versionName,
  });

  factory Versions.fromJson(Map<String, dynamic> json) {
    final version = Versions(
      id: json["id"],
      versionName: json["version_name"],
    );

    // Add books to the ToMany relationship
    final verseList =
        List<Verse>.from(json["version"].map((x) => Verse.fromJson(x)));

    final books = List<Book>.from(verseList
        .map((element) => element.bookId)
        .toSet()
        .map((e) => Book.fromVerses(
            verseList.where(((vers) => vers.bookId == e)).toList())));

    version.books.addAll(books);

    return version;
  }

  // Map<String, dynamic> toJson() => {
  //       "id": id,
  //       "version_name": versionName,
  //       // "version": List<dynamic>.from(books.map((x) => x.toJson())),
  //     };
}

@Entity()
class Verse {
  @Id()
  int? uid;
  int id;
  int bookId;
  int chapter;
  int verse;
  String text;
  String translationId;
  // String bookTag;
  String bookName;
  String testament;

  Verse({
    required this.id,
    required this.bookId,
    required this.chapter,
    required this.verse,
    required this.text,
    required this.translationId,
    // required this.bookTag,
    required this.bookName,
    required this.testament,
  });

  factory Verse.fromJson(Map<String, dynamic> json) => Verse(
        id: json["id"],
        bookId: json["book_id"],
        chapter: json["chapter"],
        verse: json["verse"],
        text: json["text"],
        translationId: json["translation_id"],
        // bookTag: json["book_tag"],
        bookName: json["book_name"],
        // bookName:utf8.decode( Uint8List.fromList(json["book_name"].codeUnits)),
        testament: json["testament"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "book_id": bookId,
        "chapter": chapter,
        "verse": verse,
        "text": text,
        "translation_id": translationId,
        // "book_tag": bookTag,
        "book_name": bookName,
        "testament": testament,
      };
}

class Quotation {
  int chapter;
  int verse;
  String? text;
  int versionId;
  // String? bookTag;
  int bookId;

  Quotation(
      {/* required */ this.chapter = 0,
      /* required */ this.verse = 0,
      /* required */ this.text,
      /* required */ this.versionId = 100,
      // /* required */ this.bookTag,
      this.bookId = 0});

  Quotation copyWith({
    int? chapter,
    int? verse,
    String? text,
    int? versionId,
    int? bookId,
  }) {
    return Quotation(
      chapter: chapter ?? this.chapter,
      verse: verse ?? this.verse,
      text: text ?? this.text,
      versionId: versionId ?? this.versionId,
      bookId: bookId ?? this.bookId,
    );
  }
}

@Entity()
class Book {
  @Id()
  int? uid;
  // /* final */ int chapters;
  final chapters = ToMany<Chapter>();
  /* final */ String translationId;
  // /* final */ String tag;
  /* final */ String name;
  /* final */ String testament;
  Book({
    // required this.chapters,
    required this.translationId,
    //  required this.tag,
    required this.name,
    required this.testament,
  });

  factory Book.fromVerses(List<Verse> verses /* ,int bookid */) {
    // final book = verses.where((element) => element.bookId == bookid,);
    final book = Book(
        // chapters: verses.map((e) => e.chapter).toSet().length,
        translationId: verses.first.translationId,
        // tag: verses.first.bookTag,
        testament: verses.first.testament,
        name: verses.first.bookName);

    final chapters = List<Chapter>.from(verses
        .map((element) => (element.chapter)).toSet()
        .toList()
        .map((e) => Chapter.fromVerses(
            verses.where(((vers) => vers.chapter == e)).toList())));
    book.chapters.addAll(chapters);
    return book;
  }
}

@Entity()
class Chapter {
  @Id()
  int? uid;
  int id;
  /* final */ int chapter;
  final verses = ToMany<Verse>();
  /* final */ String translationId;
  // /* final */ String tag;
  // /* final */ String name;
  /* final */ String testament;
  Chapter({
    required this.id,
    required this.chapter,
    required this.translationId,
    //  required this.tag,
    // required this.name,
    required this.testament,
  });

  factory Chapter.fromVerses(List<Verse> verses /* ,int bookid */) {
    // final book = verses.where((element) => element.bookId == bookid,);
    final chapter = Chapter(
      id: verses.first.id,
      chapter: verses.first.chapter,
      translationId: verses.first.translationId,
      // tag: verses.first.bookTag,
      testament: verses.first.testament,
      // name: verses.first.bookName
    );
    chapter.verses.addAll(verses);
    return chapter;
  }
}
