// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'bible_reader/domain/scripture_models.dart';
import 'favorites/domain/favorite.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1415826168774251796),
    name: 'Versions',
    lastPropertyId: const obx_int.IdUid(3, 2565655620986255551),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2117693414833873188),
        name: 'id',
        type: 6,
        flags: 32808,
        indexId: const obx_int.IdUid(1, 5262188187373121618),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3420780069434401457),
        name: 'uid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2565655620986255551),
        name: 'versionName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 6358848946683929322),
        name: 'books',
        targetId: const obx_int.IdUid(3, 4370676525116907314),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4370676525116907314),
    name: 'Book',
    lastPropertyId: const obx_int.IdUid(6, 8718448851480239110),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 525048129981325558),
        name: 'uid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3255892841249259231),
        name: 'translationId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3669181742645062340),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8718448851480239110),
        name: 'testament',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 82257534153918868),
        name: 'chapters',
        targetId: const obx_int.IdUid(5, 5972690017555032954),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2010173576889042204),
    name: 'Verse',
    lastPropertyId: const obx_int.IdUid(10, 2387146028606243561),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2443602858341774035),
        name: 'uid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7866875413030206183),
        name: 'id',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5621591918440069037),
        name: 'bookId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4116737088001757109),
        name: 'chapter',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8442293153341803788),
        name: 'verse',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1392209299130579374),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 965278367771143388),
        name: 'translationId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1177745911894806754),
        name: 'bookName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2387146028606243561),
        name: 'testament',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 5972690017555032954),
    name: 'Chapter',
    lastPropertyId: const obx_int.IdUid(5, 8018091953119835796),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7119934525917675911),
        name: 'uid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5159499235635947412),
        name: 'id',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2397712485352771910),
        name: 'chapter',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6004547672417794750),
        name: 'translationId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8018091953119835796),
        name: 'testament',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(4, 8516526038749981424),
        name: 'verses',
        targetId: const obx_int.IdUid(4, 2010173576889042204),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7311237891295714376),
    name: 'Favorite',
    lastPropertyId: const obx_int.IdUid(2, 3822119097469718663),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4810347590858260278),
        name: 'uid',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3822119097469718663),
        name: 'date',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 7311237891295714376),
    lastIndexId: const obx_int.IdUid(1, 5262188187373121618),
    lastRelationId: const obx_int.IdUid(4, 8516526038749981424),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [5845052180651136447],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      8706766543042316534,
      7463265076415335753,
      3669499377841723803,
      1437886001785354259,
      8435243719959751722,
      7933284848741564750,
      5437053447278113094,
      1330780005739473745,
      799350210711289304,
      4193737162723846339,
      1099943180880427059,
      3995458075883154341,
      903600397379637992,
    ],
    retiredRelationUids: const [462233829848366501],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Versions: obx_int.EntityDefinition<Versions>(
      model: _entities[0],
      toOneRelations: (Versions object) => [],
      toManyRelations:
          (Versions object) => {
            obx_int.RelInfo<Versions>.toMany(1, object.uid!): object.books,
          },
      getId: (Versions object) => object.uid,
      setId: (Versions object, int id) {
        object.uid = id;
      },
      objectToFB: (Versions object, fb.Builder fbb) {
        final versionNameOffset = fbb.writeString(object.versionName);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.uid ?? 0);
        fbb.addOffset(2, versionNameOffset);
        fbb.finish(fbb.endTable());
        return object.uid ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final versionNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = Versions(id: idParam, versionName: versionNameParam)
          ..uid = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            6,
          );
        obx_int.InternalToManyAccess.setRelInfo<Versions>(
          object.books,
          store,
          obx_int.RelInfo<Versions>.toMany(1, object.uid!),
        );
        return object;
      },
    ),
    Book: obx_int.EntityDefinition<Book>(
      model: _entities[1],
      toOneRelations: (Book object) => [],
      toManyRelations:
          (Book object) => {
            obx_int.RelInfo<Book>.toMany(3, object.uid!): object.chapters,
          },
      getId: (Book object) => object.uid,
      setId: (Book object, int id) {
        object.uid = id;
      },
      objectToFB: (Book object, fb.Builder fbb) {
        final translationIdOffset = fbb.writeString(object.translationId);
        final nameOffset = fbb.writeString(object.name);
        final testamentOffset = fbb.writeString(object.testament);
        fbb.startTable(7);
        fbb.addInt64(0, object.uid ?? 0);
        fbb.addOffset(2, translationIdOffset);
        fbb.addOffset(4, nameOffset);
        fbb.addOffset(5, testamentOffset);
        fbb.finish(fbb.endTable());
        return object.uid ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final translationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final testamentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = Book(
            translationId: translationIdParam,
            name: nameParam,
            testament: testamentParam,
          )
          ..uid = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            4,
          );
        obx_int.InternalToManyAccess.setRelInfo<Book>(
          object.chapters,
          store,
          obx_int.RelInfo<Book>.toMany(3, object.uid!),
        );
        return object;
      },
    ),
    Verse: obx_int.EntityDefinition<Verse>(
      model: _entities[2],
      toOneRelations: (Verse object) => [],
      toManyRelations: (Verse object) => {},
      getId: (Verse object) => object.uid,
      setId: (Verse object, int id) {
        object.uid = id;
      },
      objectToFB: (Verse object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final translationIdOffset = fbb.writeString(object.translationId);
        final bookNameOffset = fbb.writeString(object.bookName);
        final testamentOffset = fbb.writeString(object.testament);
        fbb.startTable(11);
        fbb.addInt64(0, object.uid ?? 0);
        fbb.addInt64(1, object.id);
        fbb.addInt64(2, object.bookId);
        fbb.addInt64(3, object.chapter);
        fbb.addInt64(4, object.verse);
        fbb.addOffset(5, textOffset);
        fbb.addOffset(6, translationIdOffset);
        fbb.addOffset(8, bookNameOffset);
        fbb.addOffset(9, testamentOffset);
        fbb.finish(fbb.endTable());
        return object.uid ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final bookIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final chapterParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final verseParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final translationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final bookNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final testamentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final object = Verse(
            id: idParam,
            bookId: bookIdParam,
            chapter: chapterParam,
            verse: verseParam,
            text: textParam,
            translationId: translationIdParam,
            bookName: bookNameParam,
            testament: testamentParam,
          )
          ..uid = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            4,
          );

        return object;
      },
    ),
    Chapter: obx_int.EntityDefinition<Chapter>(
      model: _entities[3],
      toOneRelations: (Chapter object) => [],
      toManyRelations:
          (Chapter object) => {
            obx_int.RelInfo<Chapter>.toMany(4, object.uid!): object.verses,
          },
      getId: (Chapter object) => object.uid,
      setId: (Chapter object, int id) {
        object.uid = id;
      },
      objectToFB: (Chapter object, fb.Builder fbb) {
        final translationIdOffset = fbb.writeString(object.translationId);
        final testamentOffset = fbb.writeString(object.testament);
        fbb.startTable(6);
        fbb.addInt64(0, object.uid ?? 0);
        fbb.addInt64(1, object.id);
        fbb.addInt64(2, object.chapter);
        fbb.addOffset(3, translationIdOffset);
        fbb.addOffset(4, testamentOffset);
        fbb.finish(fbb.endTable());
        return object.uid ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final chapterParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final translationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final testamentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = Chapter(
            id: idParam,
            chapter: chapterParam,
            translationId: translationIdParam,
            testament: testamentParam,
          )
          ..uid = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            4,
          );
        obx_int.InternalToManyAccess.setRelInfo<Chapter>(
          object.verses,
          store,
          obx_int.RelInfo<Chapter>.toMany(4, object.uid!),
        );
        return object;
      },
    ),
    Favorite: obx_int.EntityDefinition<Favorite>(
      model: _entities[4],
      toOneRelations: (Favorite object) => [],
      toManyRelations: (Favorite object) => {},
      getId: (Favorite object) => object.uid,
      setId: (Favorite object, int id) {
        object.uid = id;
      },
      objectToFB: (Favorite object, fb.Builder fbb) {
        fbb.startTable(3);
        fbb.addInt64(0, object.uid ?? 0);
        fbb.addInt64(1, object.date);
        fbb.finish(fbb.endTable());
        return object.uid ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final object = Favorite(date: dateParam)
          ..uid = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            4,
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Versions] entity fields to define ObjectBox queries.
class Versions_ {
  /// See [Versions.id].
  static final id = obx.QueryIntegerProperty<Versions>(
    _entities[0].properties[0],
  );

  /// See [Versions.uid].
  static final uid = obx.QueryIntegerProperty<Versions>(
    _entities[0].properties[1],
  );

  /// See [Versions.versionName].
  static final versionName = obx.QueryStringProperty<Versions>(
    _entities[0].properties[2],
  );

  /// see [Versions.books]
  static final books = obx.QueryRelationToMany<Versions, Book>(
    _entities[0].relations[0],
  );
}

/// [Book] entity fields to define ObjectBox queries.
class Book_ {
  /// See [Book.uid].
  static final uid = obx.QueryIntegerProperty<Book>(_entities[1].properties[0]);

  /// See [Book.translationId].
  static final translationId = obx.QueryStringProperty<Book>(
    _entities[1].properties[1],
  );

  /// See [Book.name].
  static final name = obx.QueryStringProperty<Book>(_entities[1].properties[2]);

  /// See [Book.testament].
  static final testament = obx.QueryStringProperty<Book>(
    _entities[1].properties[3],
  );

  /// see [Book.chapters]
  static final chapters = obx.QueryRelationToMany<Book, Chapter>(
    _entities[1].relations[0],
  );
}

/// [Verse] entity fields to define ObjectBox queries.
class Verse_ {
  /// See [Verse.uid].
  static final uid = obx.QueryIntegerProperty<Verse>(
    _entities[2].properties[0],
  );

  /// See [Verse.id].
  static final id = obx.QueryIntegerProperty<Verse>(_entities[2].properties[1]);

  /// See [Verse.bookId].
  static final bookId = obx.QueryIntegerProperty<Verse>(
    _entities[2].properties[2],
  );

  /// See [Verse.chapter].
  static final chapter = obx.QueryIntegerProperty<Verse>(
    _entities[2].properties[3],
  );

  /// See [Verse.verse].
  static final verse = obx.QueryIntegerProperty<Verse>(
    _entities[2].properties[4],
  );

  /// See [Verse.text].
  static final text = obx.QueryStringProperty<Verse>(
    _entities[2].properties[5],
  );

  /// See [Verse.translationId].
  static final translationId = obx.QueryStringProperty<Verse>(
    _entities[2].properties[6],
  );

  /// See [Verse.bookName].
  static final bookName = obx.QueryStringProperty<Verse>(
    _entities[2].properties[7],
  );

  /// See [Verse.testament].
  static final testament = obx.QueryStringProperty<Verse>(
    _entities[2].properties[8],
  );
}

/// [Chapter] entity fields to define ObjectBox queries.
class Chapter_ {
  /// See [Chapter.uid].
  static final uid = obx.QueryIntegerProperty<Chapter>(
    _entities[3].properties[0],
  );

  /// See [Chapter.id].
  static final id = obx.QueryIntegerProperty<Chapter>(
    _entities[3].properties[1],
  );

  /// See [Chapter.chapter].
  static final chapter = obx.QueryIntegerProperty<Chapter>(
    _entities[3].properties[2],
  );

  /// See [Chapter.translationId].
  static final translationId = obx.QueryStringProperty<Chapter>(
    _entities[3].properties[3],
  );

  /// See [Chapter.testament].
  static final testament = obx.QueryStringProperty<Chapter>(
    _entities[3].properties[4],
  );

  /// see [Chapter.verses]
  static final verses = obx.QueryRelationToMany<Chapter, Verse>(
    _entities[3].relations[0],
  );
}

/// [Favorite] entity fields to define ObjectBox queries.
class Favorite_ {
  /// See [Favorite.uid].
  static final uid = obx.QueryIntegerProperty<Favorite>(
    _entities[4].properties[0],
  );

  /// See [Favorite.date].
  static final date = obx.QueryIntegerProperty<Favorite>(
    _entities[4].properties[1],
  );
}
