// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
// To parse this JSON data, do
//
//     final kjv = kjvFromJson(jsonString);

import 'dart:convert';
import 'package:objectbox/objectbox.dart';


class Quotation {
  int chapter;
  int verse;
  String? text;
  int versionId;
  // String? bookTag;
  int bookId;

  Quotation(
      {/* required */ this.chapter = 0,
      /* required */ this.verse = 0,
      /* required */ this.text,
      /* required */ this.versionId = 100,
      // /* required */ this.bookTag,
      this.bookId = 0});

  Quotation copyWith({
    int? chapter,
    int? verse,
    String? text,
    int? versionId,
    int? bookId,
  }) {
    return Quotation(
      chapter: chapter ?? this.chapter,
      verse: verse ?? this.verse,
      text: text ?? this.text,
      versionId: versionId ?? this.versionId,
      bookId: bookId ?? this.bookId,
    );
  }
}


